### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by jovo** [openconnectome/SIMPLEX#1]
for here: http://docs.neurodata.io/SIMPLEX/Q3/2016-site_visit.html#pubs
let's make a list of whether each of them acknowledges GRAPHS & SIMPLEX (they all should acknowledge both; except 3, which is already published).

the bottom of http://jovo.me/ has the text that they should say (only the 1st 2 grants, not the last).

**Comment by MrAE** [comment]
## Acknowledgments in publications
1. No Dice.
2. No Dice.
3. Already Published. 
4. No Dice.
5. No Dice.
6. Dice.
7. No Dice.
