### ISSUE TITLE
update cs.html

### ISSUE THREAD

**Issue by jovo** [openconnectome/SIMPLEX#10]
http://docs.neurodata.io/ndintro/cs.html

look at the current ndintro slides,
and _sketch_ how to extend them for the "CS" slides,
essentially, including:
- matrix stuff
- graph stuff
- clarity stuff
- mri stuff

sketch = make an outline, but don't actually make any slides!

**Comment by gkiar** [comment]
The following is formatted as follows:
- [cs slide] <- [intro slide(s) contributing]

I think the CS.html slideshow should look like this:
- 1 (intro) <- 1 (intro)
- 2 (discovery) <- 8 (discovery)
- 3 (methods) <- 10 (paper fig 0)  worth noting, I really don't like this figure as is so will beautify, too. Hopefully in time for the paper. 😄 
- 4 (store) as existing CS slide 6
- 5-12 (store) <- 11-18 (store)
- 13-14 (store: ramon, grute) as existing CS slide 8-9
- 15-18 (explore) <- 19-21 (explore)
- 19-20 (explore: gx, vs) as existing CS slide 19-20
- 21-23 (analyze) <- 22-24 (analyze)
- 24 (analyze) as existing CS slide 25
- 25-31 (analyze) as existing CS 27-33
- 32-34 (analyze) as existing CS 36-38
- 35-36 (references) as existing CS 42-43
- 37 (people) as existing CS 44

Thoughts?

**Comment by jovo** [comment]
sorry, i don't quite understand.

can you make a markdown file,
use #'s for sections,
and - for slides
(ie, no need to include any details about slide contents)
slides can be labeled with existing slide numbers if that is helpful.

also, look at the current ndintro slides,
they are mid-flux, but the aesthetic is beautiful!

the next thing i will do after fixing the content and the titles to all be
"action titles"
is to make the figures "blend" (meaning, have no background).
but, that will take some work, and we won't get there before SIMPLEX.

On Monday, June 6, 2016, Greg Kiar notifications@github.com wrote:

> The following is formatted as follows:
> - [cs slide] <- [intro slide(s) contributing]
> 
> I think the CS.html slideshow should look like this:
> - 1 (intro) <- 1 (intro)
> - 2 (discovery) <- 8 (discovery)
> - 3 (methods) <- 10 (paper fig 0) worth noting, I really don't like
>   this figure as is so will beautify, too. Hopefully in time for the paper.
>   😄
> - 4 (store) as existing CS slide 6
> - 5-12 (store) <- 11-18 (store)
> - 13-14 (store: ramon, grute) as existing CS slide 8-9
> - 15-18 (explore) <- 19-21 (explore)
> - 19-20 (explore: gx, vs) as existing CS slide 19-20
> - 21-23 (analyze) <- 22-24 (analyze)
> - 24 (analyze) as existing CS slide 25
> - 25-31 (analyze) as existing CS 27-33
> - 32-34 (analyze) as existing CS 36-38
> - 35-36 (references) as existing CS 42-43
> - 37 (people) as existing CS 44
> 
> Thoughts?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#issuecomment-223993312,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjctA5axDg8COmRJno6qZdiQhkSCx3ks5qJDv4gaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by gkiar** [comment]
I did look at the existing ndintro slides (those are exactly what I was referencing throughout the list). I'll make this a markdown file instead.

**Comment by jovo** [comment]
yah, i know, i just couldn't follow the logic.
it is my bad, i was saying that what you did was good.
i just need a little more help....

On Tue, Jun 7, 2016 at 2:48 PM, Greg Kiar notifications@github.com wrote:

> I did look at the existing ndintro slides (those are exactly what I was
> referencing throughout the list). I'll make this a markdown file instead.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#issuecomment-224269726,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjciHo1qmyQS5gdAS8gRkUvHfAInzRks5qJWiOgaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by gkiar** [comment]
No worries, check out the file created by commit https://github.com/neurodata/SIMPLEX/commit/4417b289bf5cf015bfb7c6af5b2f76aaa8eebe68 and let me know if that is more clear :)

**Comment by jovo** [comment]
pretty great!

one concern i have for us: i plan to continuously update ndintro.

is there something like \input{.}, such that we don't have to copy and
paste?
i don't want to make changes, and then you have to find them and update,
etc.

i think iframe might do the trick?
but i don't know....

then, we could make 1 _master_,
and then we could dynamically generate slide decks that were subsets.

wanna check that out?
(that's a real question, another option is for us to just suck it up, not
sure which is better)

On Tuesday, June 7, 2016, Greg Kiar notifications@github.com wrote:

> No worries, check out the file created by commit 4417b28
> https://github.com/neurodata/SIMPLEX/commit/4417b289bf5cf015bfb7c6af5b2f76aaa8eebe68
> and let me know if that is more clear :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#issuecomment-224275409,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjch26W7TYli-1tsnWwKYpzQW1hyoUks5qJW3xgaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by gkiar** [comment]
Ya I'll investigate a bit and let you know. Even with iframes it will be problematic if slide numbers jump around as things are inserted or removed entirely. I forgot my laptop at home today so when I go home at lunch I'll poke at this more - reading papers until then :)

**Comment by jovo** [comment]
i took out the slide numbers.
you just have to wait a second until the page fully loads for them to go
away.

On Tuesday, June 7, 2016, Greg Kiar notifications@github.com wrote:

> Ya I'll investigate a bit and let you know. Even with iframes it will be
> problematic if slide numbers jump around as things are inserted or removed
> entirely. I forgot my laptop at home today so when I go home at lunch I'll
> poke at this more - reading papers until then :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#issuecomment-224283367,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcs4LP0554miKUBL2r7KRr7DMNH1uks5qJXTJgaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by gkiar** [comment]
I mean linking, though. I.e I may want slide 6 from ndintro currently, but you then add a slide making it slide 7, now my link will be broken until I update it.

**Comment by jovo** [comment]
we can name slides and link directly to them, rather than their numbers.
i used to do it in ndintro.  that is why slides have "name:xxx" throughout.

On Tue, Jun 7, 2016 at 4:58 PM, Greg Kiar notifications@github.com wrote:

> I mean linking, though. I.e I may want slide 6 from ndintro currently, but
> you then add a slide making it slide 7, now my link will be broken until I
> update it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#issuecomment-224307951,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcjgn2ScpZPSnGtWhhttSISVx04I1ks5qJYcfgaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by gkiar** [comment]
Good to know :)

**Comment by jovo** [comment]
slide numbers consume cognitive load.
i want to reserve it all for content.
i'm slowly removing everything except the "action title" and the data that
convinces them...

On Tuesday, June 7, 2016, Greg Kiar notifications@github.com wrote:

> Good to know :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#issuecomment-224308784,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcpyU8SUR-inKhh-D9YFK2sBNww1kks5qJYfCgaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by gkiar** [comment]
I'm definitely in favour of that as a concept, though the 1 hesitation regarding numbers specifically is that they're good hooks for questions from audience members after the talk - but I defer to your experience in terms of how useful they are vs distracting

**Comment by jovo** [comment]
in about 100 talks i've given,
nobody has ever referred to a slide number.
in the 1000 talks i've seen,
also nobody (that i can recall).

On Tuesday, June 7, 2016, Greg Kiar notifications@github.com wrote:

> I'm definitely in favour of that as a concept, though the 1 hesitation
> regarding numbers specifically is that they're good hooks for questions
> from audience members after the talk - but I defer to your experience in
> terms of how useful they are vs distracting
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#issuecomment-224321957,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjct4JAimmOg578uP7BmeGfXRkfjmdks5qJZFMgaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by gkiar** [comment]
Updated with all of this addressed in https://github.com/neurodata/ndintro/pull/16. Wasn't able to do live embedding of slides from another presentation because of a few problems. Can circle back eventually, but perfect is the enemy of good and all that...

**Comment by jovo** [comment]
brilliant, way to embrace the good!

On Friday, June 10, 2016, Greg Kiar notifications@github.com wrote:

> Closed #10 https://github.com/neurodata/SIMPLEX/issues/10.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/10#event-688788221, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcnVEnlMenAfinQo2qFXV4cMd8KIaks5qKY7IgaJpZM4It15l
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
