### ISSUE TITLE
acknowledgements part deux

### ISSUE THREAD

**Issue by jovo** [openconnectome/SIMPLEX#2]
i added another page of referenecs, and some more at the bottom.
can you each of the new ones to see whether they have GRAPHS or SIMPLEX acknowledged?

**Comment by MrAE** [comment]
Where did you add these?  I'm not finding them for some reason.

**Comment by jovo** [comment]
i failed to push, then fixed :)

On Tue, Mar 1, 2016 at 10:55 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> Where did you add these? I'm not finding them for some reason.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/2#issuecomment-191044316.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
## GRAPHS
1. Acknowledges XDATA, but not GRAPHS, no grant number.
2. Acknowledges XDATA, but not GRAPHS, no grant number.
3. Acknowledges XDATA, but not GRAPHS, no grant number.
4. Already Published. Does not acknowledge XDATA nor GRAPHS
5. Does not acknowledge XDATA nor GRAPHS. http://arxiv.org/pdf/1112.5507v4.pdf
6. Does not acknowledge XDATA nor GRAPHS. 
7.  Acknowledges XDATA, but not GRAPHS., no grant number. http://projecteuclid.org/download/pdfview_1/euclid.ejs/1420815881
8. Acknowledges XDATA, but not GRAPHS, no grant number.  http://arxiv.org/pdf/1304.7844v4.pdf
9.  Acknowledges XDATA, but not GRAPHS, no grant number. http://journal.frontiersin.org/article/10.3389/fninf.2015.00020/full
10. Does not acknowledge XDATA nor GRAPHS, but does  NIH NIBIB 1RO1EB016411-01, http://journal.frontiersin.org/article/10.3389/fninf.2015.00020/full
11. Acknowledges XDATA, but not GRAPHS, no grant number. http://arxiv.org/pdf/1311.5954v2.pdf
12. Does not acknowledge XDATA nor GRAPHS, http://arxiv.org/pdf/1409.2344v2.pdf

## SIMPLEX

#### starting from number 8.
1. Acknowledges XDATA and GRAPHS, no grant numbers. http://arxiv.org/pdf/1503.02115v3.pdf
2.  Does not acknowledge. http://arxiv.org/pdf/1502.03391v2.pdf
3.  Does Acknowledge XDATA. http://arxiv.org/pdf/1401.3813.pdf

**Comment by gkiar** [comment]
#13 introduces document containing a similar list. This is done?

**Comment by jovo** [comment]
ok, the "dont acknowledge but should" are all too late (except the last
one, which will be updated).

so, let's just mention the ones that do.

On Tue, Jul 5, 2016 at 12:22 PM, Greg Kiar notifications@github.com wrote:

> #13 https://github.com/neurodata/SIMPLEX/issues/13 introduces document
> containing a similar list. This is done?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/2#issuecomment-230528053,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjchqCX-62h_LR6Dm2OkUEfAZlXpMqks5qSoS0gaJpZM4Hktj_
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
