### ISSUE TITLE
Figs broken in ta2 Slides

### ISSUE THREAD

**Issue by MrAE** [openconnectome/SIMPLEX#8]
@jovo -- Trying to print pdfs for Shin. The figures are broken.  Did you move the figures folder?

**Comment by jovo** [comment]
yes.   sorry. can discuss when i'm there today.  the figs are now in a
folder called 'figs'
because we are using them for many things.

On Thu, Apr 21, 2016 at 10:18 AM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> Assigned #8 https://github.com/neurodata/SIMPLEX/issues/8 to @jovo
> https://github.com/jovo.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/8#event-636230569

## 

the glass is all full:  half water, half air.
neurodata.io
