### ISSUE TITLE
figure out how much money we spend a month in amazon for the last two month

### ISSUE THREAD

**Issue by jovo** [openconnectome/SIMPLEX#9]
on june 14th we ask for more money.
i'd like a good estimate of how much we spend.
we have multiple amazon accounts.

@alexbaden @kunallillaney @gkiar @disa-mhembere  might all be using different stuff

so, a couple estimates would be great:

1) how much we spend in S3 & EC2 each month
2) how much fraction of the time are we using our instances

**Comment by disa-mhembere** [comment]
I'm Alex's dependent when it comes to ec2. He can speak for me.
